title: Bhumika Sharma # your name (or website title) here
logo: "/images/profile_pic2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Proficient Data Analyst with 11+ years of overall experience
  including 5+ years of expertise in managing database programs, 
  extracting and evaluating sophisticated data, and translating 
  results into understandable terms to assist strategic business
  planning and facilitate improved operations. Effective communication 
  and time management skills help in driving project life cycles 
  and ensuring optimal data quality and integrity. Collaborates well 
  across technology. Excels at solving complex problems. 
  Takes full ownership of projects and have a strong history 
  of delivery of quality product, on time releases, on track 
  project and reporting to the executive staff 
  <br><br>
  <a href="https://www.linkedin.com/in/bhumika-k-sharma/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
