title: Bhumika Sharma # your name (or website title) here
logo: "/images/profile_pic2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Proficient Data Analyst with 11+ years of overall experience
  including 5+ years of expertise in ETL,Data Warehousing and BI Reporting.
  Effective communication and time management skills,Collaborates well 
  across technology. Excels at solving complex problems. 
  <br><br>
  <a href="https://www.linkedin.com/in/bhumika-k-sharma/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
